name: komik_indonesia
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.5
  
  get: 4.6.6
  http: 1.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#2A2F4F"
  adaptive_icon_foreground: "assets/icon/icon.png"


flutter: 
  uses-material-design: true
  assets:
  - assets/images/
